apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: paude-se-2026040601
  namespace: rhdh-app
  labels:
    app: paude
    paude.io/session-name: paude-se-2026040601
spec:
  lookupPolicy:
    local: true
